#!/bin/bash

echo ""
echo "=========================================================="
echo "  COPY THESE ENVIRONMENT VARIABLES TO RENDER"
echo "=========================================================="
echo ""
echo "📋 Environment Variables to add on Render:"
echo ""
echo "1. MONGO_URI - Your MongoDB connection string"
echo "2. JWT_SECRET - Generate with: node -e \"console.log(require('crypto').randomBytes(32).toString('hex'))\""
echo "3. CORS_ORIGIN - Your Vercel frontend URL"
echo "4. EMAIL_USER - Gmail or SMTP email"
echo "5. EMAIL_PASS - Email app password"
echo "6. OPENAI_API_KEY - For AI Assistant"
echo "7. AIRTEL_CLIENT_ID - Airtel Money API"
echo "8. AIRTEL_CLIENT_SECRET - Airtel Money API"
echo "9. AIRTEL_API_KEY - Airtel Money API"
echo "10. AFRICASTALKING_API_KEY - For SMS notifications"
echo "11. AFRICASTALKING_USERNAME - For SMS"
echo "12. GOOGLE_API_KEY - For RSS feeds"
echo "13. WEATHER_API_KEY - For construction planning"
echo "14. MAPS_API_KEY - For project locations"
echo "15. LOG_LEVEL - info"
echo ""
echo "🔹 Also add these on Vercel:"
echo "1. VITE_API_URL - Your Render backend URL"
echo "2. VITE_GOOGLE_API_KEY - For maps"
echo "3. VITE_WEATHER_API_KEY - For weather"
echo ""
echo "=========================================================="
